version: "3"

services:
  app_test:
    container_name: blog_app_test
    build:
      context: .
      dockerfile: ./Dockerfile.test
    volumes:
      - api_test:/app/src/app/
    depends_on:
      - postgres_test
    networks:
      - blog_test

  postgres_test:
    image: postgres:latest
    container_name: full_db_test_postgres
    environment:
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - POSTGRES_DB=${TEST_DB_NAME}
      - DATABASE_HOST=${TEST_DB_HOST}
    ports:
      - "5432:5432"
    volumes:
      - database_postgres_test:/var/lib/postgresql/data
    networks:
      - blog_test

volumes:
  api_test:
  database_postgres_test:

networks:
  blog_test:
    driver: bridge
